#!/bin/bash
# Build a double-clickable macOS app for the analyzer.
#
#   ./install_app.sh
#
# Creates "Golf Swing Analyzer.app" in ~/Applications. Double-clicking it opens
# a native macOS window (WKWebView) — no browser, no tabs, no address bar.
# Closing the window shuts the server down.
#
# A .app bundle is only a directory with a known layout; the "binary" can be a
# shell script. No compilation, no dependencies.

set -euo pipefail

PROJECT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
APP="$HOME/Applications/Golf Swing Analyzer.app"

rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"

cat > "$APP/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleName</key>            <string>Golf Swing Analyzer</string>
    <key>CFBundleDisplayName</key>     <string>Golf Swing Analyzer</string>
    <key>CFBundleIdentifier</key>      <string>local.golfswing.analyzer</string>
    <key>CFBundleVersion</key>         <string>1.0</string>
    <key>CFBundlePackageType</key>     <string>APPL</string>
    <key>CFBundleExecutable</key>      <string>launch</string>
    <key>LSMinimumSystemVersion</key>  <string>11.0</string>
</dict>
</plist>
PLIST

cat > "$APP/Contents/MacOS/launch" <<LAUNCH
#!/bin/bash
# Generated by install_app.sh — edit that, not this.
PROJECT="$PROJECT"
cd "\$PROJECT" || exit 1

exec "\$PROJECT/.venv/bin/python" "\$PROJECT/desktop.py"
LAUNCH

chmod +x "$APP/Contents/MacOS/launch"

# Give it a real icon if one is available; harmless if not.
if [ -f "$PROJECT/docs/appicon.icns" ]; then
    cp "$PROJECT/docs/appicon.icns" "$APP/Contents/Resources/appicon.icns"
    /usr/libexec/PlistBuddy -c "Add :CFBundleIconFile string appicon" \
        "$APP/Contents/Info.plist" >/dev/null 2>&1 || true
fi

# Clear the quarantine flag so Gatekeeper does not block the first launch.
xattr -cr "$APP" 2>/dev/null || true

echo "Installed: $APP"
echo
echo "Double-click it in ~/Applications (or drag it to your Dock)."
echo "Closing the window stops the server — nothing left running."
